"""portfolio_flash_fin

Revision ID: 203f9f3bb806
Revises: df1486d57612
Create Date: 2026-05-30 00:30:06.339483

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '203f9f3bb806'
down_revision: str | None = 'df1486d57612'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estoque_itens',
    sa.Column('estudio_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.Enum('TINTA', 'AGULHA', 'LUVA', 'PAPEL', 'PRODUTO', 'OUTRO', name='categoria_estoque'), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=False),
    sa.Column('quantidade_atual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_minima', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_custo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['estudio_id'], ['estudios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estoque_itens_estudio_id'), 'estoque_itens', ['estudio_id'], unique=False)
    op.create_index(op.f('ix_estoque_itens_id'), 'estoque_itens', ['id'], unique=False)
    op.create_table('flash_arts',
    sa.Column('estudio_id', sa.UUID(), nullable=False),
    sa.Column('artista_id', sa.UUID(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('imagem_path', sa.String(length=500), nullable=True),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tamanho_sugerido', sa.String(length=100), nullable=True),
    sa.Column('local_recomendado', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('DISPONIVEL', 'EM_NEGOCIACAO', 'RESERVADA', 'SINAL_PAGO', 'VENDIDA', 'ARQUIVADA', name='status_flash'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['artista_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['estudio_id'], ['estudios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flash_arts_estudio_id'), 'flash_arts', ['estudio_id'], unique=False)
    op.create_index(op.f('ix_flash_arts_id'), 'flash_arts', ['id'], unique=False)
    op.create_index(op.f('ix_flash_arts_status'), 'flash_arts', ['status'], unique=False)
    op.create_table('documentos',
    sa.Column('estudio_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=True),
    sa.Column('atendimento_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.Enum('POLITICA_PRIVACIDADE', 'TERMOS_USO', 'CONSENTIMENTO', 'AUTORIZACAO_IMAGEM', 'POLITICA_SINAL', 'AFTERCARE', 'OUTRO', name='tipo_documento'), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('versao', sa.String(length=20), nullable=False),
    sa.Column('assinado', sa.Boolean(), nullable=False),
    sa.Column('data_assinatura', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_assinatura', sa.String(length=45), nullable=True),
    sa.Column('trilha_aceite', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['estudio_id'], ['estudios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_estudio_id'), 'documentos', ['estudio_id'], unique=False)
    op.create_index(op.f('ix_documentos_id'), 'documentos', ['id'], unique=False)
    op.create_table('lancamentos',
    sa.Column('estudio_id', sa.UUID(), nullable=False),
    sa.Column('atendimento_id', sa.UUID(), nullable=True),
    sa.Column('artista_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', 'COMISSAO', 'SINAL', name='tipo_lancamento'), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('forma_pagamento', sa.Enum('PIX', 'DINHEIRO', 'CARTAO_DEBITO', 'CARTAO_CREDITO', 'TRANSFERENCIA', 'OUTRO', name='forma_pagamento_fin'), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'PAGO', 'CANCELADO', 'ESTORNADO', name='status_lancamento'), nullable=False),
    sa.Column('data_prevista', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_realizada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artista_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos.id'], ),
    sa.ForeignKeyConstraint(['estudio_id'], ['estudios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lancamentos_estudio_id'), 'lancamentos', ['estudio_id'], unique=False)
    op.create_index(op.f('ix_lancamentos_id'), 'lancamentos', ['id'], unique=False)
    op.create_table('portfolio',
    sa.Column('estudio_id', sa.UUID(), nullable=False),
    sa.Column('artista_id', sa.UUID(), nullable=True),
    sa.Column('atendimento_id', sa.UUID(), nullable=True),
    sa.Column('imagem_path', sa.String(length=500), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('estilo', sa.String(length=100), nullable=True),
    sa.Column('parte_corpo', sa.String(length=100), nullable=True),
    sa.Column('autorizado_publicacao', sa.Boolean(), nullable=False),
    sa.Column('visibilidade', sa.Enum('PRIVADO', 'PUBLICO', name='visibilidade_portfolio'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['artista_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos.id'], ),
    sa.ForeignKeyConstraint(['estudio_id'], ['estudios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_estudio_id'), 'portfolio', ['estudio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_id'), 'portfolio', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_id'), table_name='portfolio')
    op.drop_index(op.f('ix_portfolio_estudio_id'), table_name='portfolio')
    op.drop_table('portfolio')
    op.drop_index(op.f('ix_lancamentos_id'), table_name='lancamentos')
    op.drop_index(op.f('ix_lancamentos_estudio_id'), table_name='lancamentos')
    op.drop_table('lancamentos')
    op.drop_index(op.f('ix_documentos_id'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_estudio_id'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_flash_arts_status'), table_name='flash_arts')
    op.drop_index(op.f('ix_flash_arts_id'), table_name='flash_arts')
    op.drop_index(op.f('ix_flash_arts_estudio_id'), table_name='flash_arts')
    op.drop_table('flash_arts')
    op.drop_index(op.f('ix_estoque_itens_id'), table_name='estoque_itens')
    op.drop_index(op.f('ix_estoque_itens_estudio_id'), table_name='estoque_itens')
    op.drop_table('estoque_itens')
    # ### end Alembic commands ###
