"""initial_models

Revision ID: df1486d57612
Revises: 
Create Date: 2026-05-30 00:18:10.329517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df1486d57612'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estudios',
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('instagram', sa.String(length=100), nullable=True),
    sa.Column('logo_path', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estudios_id'), 'estudios', ['id'], unique=False)
    op.create_index(op.f('ix_estudios_slug'), 'estudios', ['slug'], unique=True)
    op.create_table('clientes',
    sa.Column('estudio_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('instagram', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('foto_path', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['estudio_id'], ['estudios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_estudio_id'), 'clientes', ['estudio_id'], unique=False)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_nome'), 'clientes', ['nome'], unique=False)
    op.create_table('usuarios',
    sa.Column('estudio_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('senha_hash', sa.String(length=500), nullable=False),
    sa.Column('tipo', sa.Enum('ADMIN', 'ARTISTA', 'RECEPCIONISTA', name='tipo_usuario'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['estudio_id'], ['estudios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_estudio_id'), 'usuarios', ['estudio_id'], unique=False)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('atendimentos',
    sa.Column('estudio_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=True),
    sa.Column('artista_id', sa.UUID(), nullable=True),
    sa.Column('status_operacional', sa.Enum('SOLICITADO', 'EM_ANALISE', 'AGUARDANDO_SINAL', 'CONFIRMADO', 'EM_ATENDIMENTO', 'FINALIZADO', 'REAGENDADO', 'CANCELADO_CLIENTE', 'CANCELADO_ESTUDIO', 'NAO_COMPARECEU', 'RETOQUE', name='status_operacional'), nullable=False),
    sa.Column('status_financeiro', sa.Enum('PENDENTE', 'SINAL_PAGO', 'PAGO_PARCIAL', 'PAGO_TOTAL', 'ISENTO', 'ESTORNADO', name='status_financeiro'), nullable=False),
    sa.Column('tipo', sa.Enum('TATUAGEM', 'CONSULTA', 'RETOQUE', 'FLASH', name='tipo_atendimento'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('parte_corpo', sa.String(length=100), nullable=True),
    sa.Column('estilo', sa.String(length=100), nullable=True),
    sa.Column('tamanho_cm', sa.String(length=50), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_sinal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('forma_pagamento', sa.Enum('PIX', 'DINHEIRO', 'CARTAO_DEBITO', 'CARTAO_CREDITO', 'TRANSFERENCIA', 'OUTRO', name='forma_pagamento'), nullable=True),
    sa.Column('notas_privadas', sa.Text(), nullable=True),
    sa.Column('data_sessao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duracao_minutos', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['artista_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['estudio_id'], ['estudios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atendimentos_artista_id'), 'atendimentos', ['artista_id'], unique=False)
    op.create_index(op.f('ix_atendimentos_cliente_id'), 'atendimentos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_atendimentos_data_sessao'), 'atendimentos', ['data_sessao'], unique=False)
    op.create_index(op.f('ix_atendimentos_estudio_id'), 'atendimentos', ['estudio_id'], unique=False)
    op.create_index(op.f('ix_atendimentos_id'), 'atendimentos', ['id'], unique=False)
    op.create_index(op.f('ix_atendimentos_status_operacional'), 'atendimentos', ['status_operacional'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_atendimentos_status_operacional'), table_name='atendimentos')
    op.drop_index(op.f('ix_atendimentos_id'), table_name='atendimentos')
    op.drop_index(op.f('ix_atendimentos_estudio_id'), table_name='atendimentos')
    op.drop_index(op.f('ix_atendimentos_data_sessao'), table_name='atendimentos')
    op.drop_index(op.f('ix_atendimentos_cliente_id'), table_name='atendimentos')
    op.drop_index(op.f('ix_atendimentos_artista_id'), table_name='atendimentos')
    op.drop_table('atendimentos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_estudio_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_clientes_nome'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_estudio_id'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_estudios_slug'), table_name='estudios')
    op.drop_index(op.f('ix_estudios_id'), table_name='estudios')
    op.drop_table('estudios')
    # ### end Alembic commands ###
